---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-load-balancer-controller-values
  namespace: kapp-controller
data:
  values.yml: |
    clusterName: rancher
    hostNetwork: false
    image:
      repository: "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-load-balancer-controller"
    enableShield: false
    enableWaf: false
    enableWafv2: true
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: aws-load-balancer-controller
  namespace: kapp-controller
spec:
  serviceAccountName: cluster-admin-sa
  fetch:
  - git:
      url: "https://github.com/aws/eks-charts"
      ref: origin/master
      subPath: "stable/aws-load-balancer-controller"

  template:
  - helmTemplate:
      namespace: kube-system
      valuesFrom:
        - configMapRef:
            name: aws-load-balancer-controller-values

  deploy:
  - kapp: {}
