#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-values
  namespace: kapp-controller
data:
  #@yaml/text-templated-strings
  values.yml: |
    controller:
      watchIngressWithoutClass: true
      (@ if data.values.ingress_ssl_passthrough: -@)
      extraArgs:
        enable-ssl-passthrough: "true"
      (@ end -@)
      ingressClassResource:
        default: true
      hostNetwork: (@= str(data.values.host_network).lower() @)
      service:
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: (@= data.values.ingress_nlb_scheme @)
          (@ if data.values.external_access_cidrs: -@)
          service.beta.kubernetes.io/load-balancer-source-ranges: (@= data.values.external_access_cidrs @)
          (@ end -@)
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: ingress-nginx
  namespace: kapp-controller
spec:
  serviceAccountName: cluster-admin-sa
  fetch:
  - git:
      url: "https://github.com/kubernetes/ingress-nginx"
      ref: refs/tags/helm-chart-4.0.18
      subPath: "charts/ingress-nginx"

  template:
  - helmTemplate:
      namespace: ingress-nginx
      valuesFrom:
        - configMapRef:
            name: ingress-nginx-values

  deploy:
  - kapp: {}
