#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-values
  namespace: kapp-controller
data:
  #@yaml/text-templated-strings
  values.yml: |
    hostname: "(@= data.values.cluster @).(@= data.values.domain @)"
    privateCA: (@= str(data.values.rancher_private_ca).lower() @)
    ingress:
      extraAnnotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      tls:
        source: (@= data.values.rancher_tls_source @)
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: rancher
  namespace: kapp-controller
spec:
  serviceAccountName: cluster-admin-sa
  fetch:
  - git:
      url: "https://github.com/nicholasmhughes/rancher"
      ref: origin/do-not-merge/release/v2.6
      subPath: "chart"

  template:
    - helmTemplate:
        namespace: cattle-system
        valuesFrom:
          - configMapRef:
              name: rancher-values

  deploy:
  - kapp:
      intoNs: cattle-system
