#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-values
  namespace: kapp-controller
data:
  #@yaml/text-templated-strings
  values.yml: |
    hostname: "(@= data.values.cluster @).(@= data.values.domain @)"
    privateCA: "false"
    ingress:
      extraAnnotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      tls:
        source: rancher
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: rancher
  namespace: kapp-controller
spec:
  serviceAccountName: cluster-admin-sa
  fetch:
  - git:
      url: "https://github.com/rancher/rancher"
      ref: refs/tags/v2.6.3
      subPath: "chart"

  template:
    - ytt:
        ignoreUnknownComments: true
        fileMarks:
          - "templates/*:exclude=true"
          - "Chart.yaml:path=Chart.bak"
        inline:
          paths:
            Chart.yaml: |
              apiVersion: v2
              name: rancher
              description: Install Rancher Server to manage Kubernetes clusters across providers.
              version: 2.6.3
              appVersion: v2.6.3
              kubeVersion: < 1.24.0-0
              home: https://rancher.com
              icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
              keywords:
                - rancher
              sources:
                - https://github.com/rancher/rancher
                - https://github.com/rancher/server-chart
              maintainers:
                - name: Rancher Labs
                  email: charts@rancher.com

    - helmTemplate:
        namespace: cattle-system
        valuesFrom:
          - configMapRef:
              name: rancher-values

  deploy:
  - kapp: {}
